pipeline:
  build:
    image: ruby:2.4.1
    environment:
     - RAILS_ENV=test
     - POSTGRESQL_HOST=database
    commands:
      - apt-get update -qq
      - apt-get install -y nodejs
      - bundle install --jobs 20 --retry 5
      - bundle exec rake db:create db:migrate
      - bundle exec rake test
  docker:
    image: plugins/docker
    repo: florian95/try_docker_rails
    tags: latest
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: delight
    when:
      status: [ success, failure ]
  
services:
  database:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
