pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/bundle
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
  build:
    image: ruby:2.4.1
    environment:
      - RAILS_ENV=test
      - POSTGRESQL_HOST=database
    commands:
      - apt-get update -qq
      - apt-get install -y nodejs
      - bundle install --jobs 20 --retry 5 --path /drone/bundle --without "development production"
      - bundle exec rake db:create db:migrate
      - bundle exec rake test
  ecr:
    image: plugins/ecr
    repo: 767874247885.dkr.ecr.eu-west-1.amazonaws.com/delight
    registry: 767874247885.dkr.ecr.eu-west-1.amazonaws.com
    secrets: [ ecr_access_key, ecr_secret_key ]
    region: eu-west-1
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: delight
    when:
      status: [ success, failure ]
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/bundle
    # Mount the cache volume, needs "Trusted"
    volumes:
      - /tmp/cache:/cache
  
services:
  database:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres

