pipeline:
  build:
    image: ruby:2.4.1
    environment:
     - RAILS_ENV=test
    commands:
      - apt-get update -qq
      - apt-get install -y build-essential
      - apt-get install -y nodejs
      - bundle install --jobs 20 --retry 5
      - bundle exec rake db:create db:migrate
      - bundle exec rspec
      
services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
