pipeline:
  build:
    image: ruby2.4.1
    environment:
     - RAILS_ENV=test
    commands:
      - bundle install
      - bundle exec rake db:create db:migrate
      - bundle exec rspec
services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
