pipeline:
  build:
    image: ruby:2.4.1
    environment:
     - RAILS_ENV=test
     - POSTGRESQL_HOST=database
    commands:
      - apt-get update -qq
      - apt-get install -y nodejs
      - bundle install --jobs 20 --retry 5 --path /tmp/bundler
      - bundle exec rake db:create db:migrate
  test:
    commands:
      - bundle exec test
   
cache:
  - /tmp/bundler

services:
  database:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
